name: Node CI

on: 
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master
      - staging
      - development

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Node.js
      uses: actions/setup-node@v3.5.1
      with:
        cache: npm
        cache-dependency-path: "package-lock.json"
        node-version: 16
    - name: Install dependencies
      run: npm ci
    - name: Lint (GitHub)
      run: npm run lint
    - name: Lint (SonarCloud)
      run: npm run lint:json
    - name: Unit tests
      run: npm run test
    - name: Transform paths in reports
      run: sed -i 's/\/home\/runner\/work\/smartlab-initiative\/smartlab-initiative/./' ./lint/report.json
    #    sed -i 's/\/home\/runner\/work\/smartlab-initiative\/smartlab-initiative/./' ./coverage/lcov.info
         # sed -i 's/\/home\/runner\/work\/smartlab-initiative\/smartlab-initiative/./' ./coverage/cobertura-coverage.xml
    #    # sed -i 's/\/home\/runner\/work\/smartlab-initiative\/smartlab-initiative/./' ./test/report.xml
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
