name: Node CI

on: 
  push:
    refs/heads:
      - master
      - staging
      - development
      - contrib

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.11.0]
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Installing dependencies
      run: |
        cd ./app
        npm install
    - name: Linting (pylint)
      run: |
        cd ./app
        npm install --save-dev eslint eslint-plugin-vue
        ./node_modules/.bin/eslint --config=../lint/.eslintrc.js --output-file=../lint/report.json --format=json "**/*.{js,vue}"
    - name: Unit testing
      run: |
        cd ./app
        npm run build --if-present
        npm test
      env:
        CI: true
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
